import { Component } from '@angular/core';
import { PlanPricingFacade } from '../facade/plan-pricing.facade';

@Component({
  selector: 'buffer-plan-pricing',
  styleUrls: ['./plan-pricing.component.css'],
  templateUrl: './plan-pricing.component.html'
})
export class PlanPricingComponent {
  public is_monthly_price = true;

  products: any[] = [
    {
      advanced: '$89',
      groupHeader: true,
      groupName: 'The Basics',
      name: 'Monthly Price',
      premium: '$59',
      pro: '$29'
    },
    { groupName: '',
      groupHeader: false,
      name: 'Social Accounts',
      pro: '10',
      premium: '15',
      advanced: '30' },
    { groupName: '',
      groupHeader: false,
      name: 'Additional Account',
      pro: '$14.25/mo',
      premium: '$21.75/mo',
      advanced: '$29.75/mo' },
    { groupName: '',
      groupHeader: false,
      name: 'Scheduled Posts Per Social Account',
      pro: '100',
      premium: 'Unlimited',
      advanced: 'Unlimited' },
    { groupName: '',
      groupHeader: false,
      name: 'Team members',
      pro: '2',
      premium: '5',
      advanced: '10' },
    { groupName: '',
      groupHeader: false,
      name: 'Additional team member',
      pro: '$11.25/mo',
      premium: '$11.25/mo',
      advanced: '$11.25/mo' },
    {
      groupName: 'Social Networks',
      groupHeader: true,
      name: 'Facebook',
      pro: false,
      premium: true,
      advanced: true
    },
    { groupName: '',
      groupHeader: false,
      name: 'Instagram',
      pro: true,
      premium: true,
      advanced: true },
    { groupName: '',
      groupHeader: false,
      name: 'LinkedIn',
      pro: true,
      premium: false,
      advanced: false },
    { groupName: '',
      groupHeader: false,
      name: 'Twitter',
      pro: true,
      premium: true,
      advanced: true },
    { groupName: '',
      groupHeader: false,
      name: 'Pinterest',
      pro: true,
      premium: true,
      advanced: true },
    {
      groupName: 'Planning and Scheduling',
      groupHeader: true,
      name: 'Directly schedule posts',
      pro: true,
      premium: true,
      advanced: true
    },
    { groupName: '',
      groupHeader: false,
      name: 'calendar view',
      pro: true,
      premium: true,
      advanced: true },
    { groupName: '',
      groupHeader: false,
      name: 'Create and manage draft posts',
      pro: false,
      premium: true,
      advanced: true },
    { groupName: '',
      groupHeader: false,
      name: 'Posts report',
      pro: 'Full history',
      premium: 'Full history',
      advanced: 'Full history' },
    {
      groupName: 'Team Management',
      groupHeader: true,
      name: 'Invite additional users',
      pro: true,
      premium: true,
      advanced: true
    },
    { groupName: '',
      groupHeader: false,
      name: 'Assign access and permission',
      pro: false,
      premium: true,
      advanced: true },
    { groupName: 'Insights',
      groupHeader: true,
      name: 'Performance Overview',
      pro: true,
      premium: true,
      advanced: true },
    { groupName: '',
      groupHeader: false,
      name: 'Individual Post Analytics',
      pro: true,
      premium: true,
      advanced: true },
    { groupName: '',
      groupHeader: false,
      name: 'Demographics',
      pro: true,
      premium: true,
      advanced: true },
    { groupName: '',
      groupHeader: false,
      name: 'Enganement',
      pro: true,
      premium: true,
      advanced: true },
    { groupName: '',
      groupHeader: false,
      name: 'Reach',
      pro: true,
      premium: true,
      advanced: true },
    { groupName: '',
      groupHeader: false,
      name: 'Page Performance',
      pro: true,
      premium: true,
      advanced: true },
    { groupName: '',
      groupHeader: false,
      name: 'Hashtag Performance',
      pro: true,
      premium: true,
      advanced: true },
    { groupName: '',
      groupHeader: false,
      name: 'Instagram stories analytics',
      pro: true,
      premium: true,
      advanced: true },

    { groupName: 'Reports',
      groupHeader: true,
      name: 'Charts exports',
      pro: true,
      premium: true,
      advanced: true },
    { groupName: '',
      groupHeader: false,
      name: 'Analytics exports',
      pro: 'XLS',
      premium: 'XLS, PDF',
      advanced: 'XLS, PDF' },
    { groupName: '',
      groupHeader: false,
      name: 'Email reports',
      pro: true,
      premium: true,
      advanced: true },
    { groupName: '',
      groupHeader: false,
      name: 'Enganement',
      pro: true,
      premium: true,
      advanced: true },
    { groupName: '',
      groupHeader: false,
      name: 'Reach',
      pro: true,
      premium: true,
      advanced: true },
    { groupName: '',
      groupHeader: false,
      name: 'Page Performance',
      pro: true,
      premium: true,
      advanced: true }
  ];

  constructor (private readonly facade: PlanPricingFacade) {}

  public scrollIntoView (): void {
    const element = this.facade.getElement('comparisonTable');

    element.scrollIntoView({
      behavior: 'smooth',
      block: 'start'
    });
  }
}
